### ISSUE TITLE
math.floor

### ISSUE THREAD

**Issue by Alexufo** [ejb/progressor.js#6]
Now 900px  progress bar  covered only 100 steps.
` value = Math.floor((100 / this._media.duration) * this._media.currentTime);`

I think Math.floor is not needed. Percent value have 4 number after dot. 39.9434% and progress bar will be more precisely.

**Comment by ejb** [comment]
Seems reasonable. I'm no longer actively maintaining this library (it's going to be phased out in a future rewrite of oTranscribe, but you are welcome to submit a pull request.

**Comment by ejb** [comment]
This is added in 96d8e8413c066effc316d8b8e6393d1b0b6b2b1c
