### ISSUE TITLE
Demos are not working

### ISSUE THREAD

**Issue by helloiamlukas** [ejb/progressor.js#9]
Looks like the provided demos aren't working anymore as Github can't be used as CDN.

**Comment by ejb** [comment]
Omg I can't believe drake is posting issues in my repo! I love hotline bling!

Thanks for flagging – the issue was actually that I forgot to merge https://github.com/ejb/progressor.js/commit/0954b9c209194dab288b892c3caad69654119bb7 into the gh-pages branch. Should be fixed now.
